### PR TITLE
Update to MaterialPress

### PR DESCRIPTION
**Pull request by danielhickman**
Updated Footer with Copyright and three widgets; stays at bottom, Header
updated, and Articles are now Cards with actions

### CODE REVIEW

**Comment by danielhickman** [comment]
See [redacted] for the finished product. Also, because this project seems to be in disrepair, could you add me as a contributor. I would be glad to take this project on and as seen from today's pull request, I am experienced with MaterializeCSS and would like to put some work into it.

**Comment by Dogfalo** [comment]
:+1: It would be a shame to see this project die off.

**Comment by onerinas** [comment]
i can see @danielhickman as a contributor. so i guess you didn't make a separate repo ( i cant see in @danielhickman's profile either - may be in some other name? )
is this repo still active? i would like to follow up

**Comment by danielhickman** [comment]
Sadly it's not active. I've had personal things arise and only have time
for design.

**Comment by alexpatin** [comment]
Hey @onerinas -- unfortunately I just haven't had the time to sit down and hash this out. It's something I'd still like to do at some point, but unfortunately I can't provide a solid time when that will be. Of course I would love for that to be sooner than later.

There are a few open source and commercial options available elsewhere for the time being. Thanks for your interest.

**Comment by onerinas** [comment]
okay :)

**Pull request merged**
